name: Atualizar GIF do Tetris

on:
  schedule:
    - cron: "0 * * * *" # Roda a cada hora
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install numpy imageio matplotlib

      - name: Gerar novo GIF do Tetris
        run: python tetris.py

      - name: Commit e push do novo GIF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tetris.gif
          git commit -m "Atualizando GIF do Tetris"
          git push
